
#spring:
#  application:
#    name: mcroservice-order-02  #服务名

server:
  port: 8445
spring:
  application:
    name: cloud-gateway-01
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: payment-route01
#          uri:lb://Payment-Provider
#          predicates:
#            - Path=/payment/get/**
#            - After=2021-11-24 T21:11:46.662+08:00[Asia/Shanghai]
#            断言自行设置可access的时间，这是设置在 20211124 8：后可access

#        - id:payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
#          uri:http://localhost:8010
#
##         uri: http://localhost:8010
#          predicates:
#            - Path=/payment/get/** # 断言，路径相匹配的进行路由
#        - id: payment_route2
#          uri: http://localhost:8010
#          predicates:
#             Path=/payment/lb/** #断言,路径相匹配的进行路由



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/

